### ISSUE TITLE
[mimir-distributed] extraEnvFrom Options for s3 secrets in mimir config file. 

### ISSUE THREAD

**Issue by brandonrjacobs** [grafana/helm-charts#1314] opened 2022-04-27 21:53 UTC
Currently the only supported option is located in the Nginx values path:

```yaml

# Configuration for nginx gateway
nginx:
  # -- Environment variables to add to the nginx pods
  extraEnv: []
  # -- Environment variables from secrets or configmaps to add to the nginx pods
  extraEnvFrom: []
```

Given I am using `s3` as the `blocks_storage` I would like to set the S3 credentials as environment variables as such in the config:

```yaml
ingester:
  extraEnvFrom:
    - secretRef:
        name: s3-auth
mimir:
  config: |
    blocks_storage:
          backend: s3
          tsdb:
            dir: /data/tsdb
          bucket_store:
            sync_dir: /data/tsdb-sync
          s3:
            endpoint: <endpoint>
            bucket_name: <bucket>
            access_key_id: ${S3_ACCESS_KEY}
            secret_access_key: ${S3_ACCESS_SECRET}
            insecure: true
```
Given this configuration is needed by the `ingester` and I believe other services, is there a way for this to work with the chart? I know loki-distributed has this capability and we currently do that there. Or am I missing something with the current implementation?

**Comment by krajorama** [comment] 2022-04-28 10:07
duplicate of #1287 and related to #1150 . We'll be implementing this. Note: we'll have to set the CLI flag `-config.exand-env=true` https://grafana.com/docs/mimir/latest/operators-guide/configuring/reference-configuration-parameters/#use-environment-variables-in-the-configuration

**Comment by brandonrjacobs** [comment] 2022-04-28 12:38
@krajorama are you open to contributions for this? or is it already in development?

**Comment by krajorama** [comment] 2022-04-28 12:59
Not in development, just planning, there's some other bigger works going on currently. After our launch we received a bunch of issues, so I'm trying to organize things into groups, the issues listed above seem to fit together nicely. Open to contributions just be prepared to rebase a couple of times possibly.

**Comment by brandonrjacobs** [comment] 2022-04-28 13:14
Thanks for the info. I don't mind rebasing and can put something together for this.

**Comment by krajorama** [comment] 2022-04-28 14:07
Cool, appreciate it. As far as I can see all of these can be added in a backwards compatible manner. Anything breaking would have to be added to https://github.com/grafana/helm-charts/issues/1309 and released later.

**Closed** 2022-06-04 14:03 UTC
