### ISSUE TITLE
Problem in promtail helm installation

### ISSUE THREAD

**Issue by sam75m** [grafana/helm-charts#1392] opened 2022-05-19 19:37 UTC
I edited values.yaml and added basic auth to reach my remote loki server in this format:
```
  extraScrapeConfigs: |
      basic_auth:
         username: lokiuser
         password: secret
```
but pods are crashing with this error:
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: line 77: did not find expected '-' indicator
```
list of pods:
```
NAME             READY   STATUS              RESTARTS   AGE
promtail-nqpxn   0/1     CrashLoopBackOff   3          98s
promtail-qnh5x   0/1     CrashLoopBackOff   3          99s
```

**Comment by kucerakk** [comment] 2022-05-23 13:58
I experience the same issue. The problem is, that in the following update the extra client config part became an array/list (it used to be a string):
https://github.com/grafana/helm-charts/commit/5a990ab9883bf2c001204cf9bc867b6a286f4363

If I understand it correctly according to the config from https://grafana.com/docs/loki/latest/clients/promtail/configuration/ the clients part can now contain multiple loki instances as list elements.  However in the ```values.yaml``` the url part is already one element of the list + It adds the ```extraClientConfigs``` as additional elements to the ```clients``` list.

```
 clients:
      - url: {{ tpl .Values.config.lokiAddress . }}
      {{- with .Values.config.snippets.extraClientConfigs }}
      {{- toYaml . | nindent 2 }}
      {{- end }}
```

resulting to:
``` 
clients:
  - url: https://loki
  - basic_auth:
       username: lokiuser
       password: secret
```

If you keep passing the values to the chart as dictionary, then the resulting config looks like:
```
clients:
  - url: https://loki
  basic_auth:
       username: lokiuser
       password: secret
```

CORRECT config should look like:
```
clients:
  - url: https://loki
    basic_auth:
       username: lokiuser
       password: secret
  - url: https://loki2
    basic_auth:
       username: lokiuser
       password: secret
```

pls correct me If I am wrong.

**Comment by sam75m** [comment] 2022-05-24 15:37
> I experience the same issue. The problem is, that in the following update the extra client config part became an array/list (it used to be a string): [5a990ab](https://github.com/grafana/helm-charts/commit/5a990ab9883bf2c001204cf9bc867b6a286f4363)
> 
> If I understand it correctly according to the config from https://grafana.com/docs/loki/latest/clients/promtail/configuration/ the clients part can now contain multiple loki instances as list elements. However in the `values.yaml` the url part is already one element of the list + It adds the `extraClientConfigs` as additional elements to the `clients` list.
> 
> ```
>  clients:
>       - url: {{ tpl .Values.config.lokiAddress . }}
>       {{- with .Values.config.snippets.extraClientConfigs }}
>       {{- toYaml . | nindent 2 }}
>       {{- end }}
> ```
> 
> resulting to:
> 
> ```
> clients:
>   - url: https://loki
>   - basic_auth:
>        username: lokiuser
>        password: secret
> ```
> 
> If you keep passing the values to the chart as dictionary, then the resulting config looks like:
> 
> ```
> clients:
>   - url: https://loki
>   basic_auth:
>        username: lokiuser
>        password: secret
> ```
> 
> CORRECT config should look like:
> 
> ```
> clients:
>   - url: https://loki
>     basic_auth:
>        username: lokiuser
>        password: secret
>   - url: https://loki2
>     basic_auth:
>        username: lokiuser
>        password: secret
> ```
> 
> pls correct me If I am wrong.

How can I fix this issue?

**Comment by jfoechsler** [comment] 2022-05-24 16:01
I think it's the same as reported in https://github.com/grafana/helm-charts/issues/1214

**Comment by sam75m** [comment] 2022-05-24 16:02
@kucerakk I tried again with changing client part to:
```
       clients:
      - url: {{ tpl .Values.config.lokiAddress . }}
        {{- with .Values.config.snippets.extraClientConfigs }}
        {{- toYaml . | nindent 2 }}
        {{- end }}

```
Still have same issue with same log.

**Comment by trevorwhitney** [comment] 2022-05-24 16:35
Thanks for reporting this. I think the best approach here is probably to remove both `lokiAddress` and `extraClientConfigs` and instead expose a single value like `clientConfigs` that takes an array of objects defining client configs. Let's pick up the conversation in https://github.com/grafana/helm-charts/issues/1214 (thanks for linking that @jfoechsler!). Closing this one.

**Closed by trevorwhitney** 2022-05-24 16:35 UTC
