### ISSUE TITLE
logLevel is empty on sc-dashboard and crashes it.

### ISSUE THREAD

**Issue by marrau** [grafana/helm-charts#1627] opened 2022-07-20 14:39 UTC
The pod-template contains a broken configuration for the Sidecar-LogLevel.

I found the following Code where the error occurs. It uses ".Values.sidecar.logLevel" in the condition, but ".Values.sidecar.dashboards.logLevel" for the actual value (which does not exists and results in an empty Environment Variable)

https://github.com/grafana/helm-charts/blob/ef1163293055c47e113f8aec6f022dd232fe0298/charts/grafana/templates/_pod.tpl#L201-L204

Not sure how to resolve this error: Defaulting the Output in the Pod-Template, Set appropriate Value in values.yaml or else?

Workaround is to put this into your values.yaml:
```yaml
sidecar:
  dashboards:
    logLevel: INFO
```

**Comment by Legion2** [comment] 2022-07-20 14:40
duplicate of #1626

**Comment by ftpd** [comment] 2022-07-20 15:03
https://github.com/grafana/helm-charts/pull/1628

**Comment by ftpd** [comment] 2022-07-21 19:52
Merged. @marrau, maybe close the issue?

**Closed** 2022-07-21 19:55 UTC
