### ISSUE TITLE
can't update grafana helmchart to version 6.44.9 from 6.43.5 using flux2

### ISSUE THREAD

**Issue by mo-saeed** [grafana/helm-charts#2019] opened 2022-11-29 15:08 UTC
Hi,

flux2 is not able to upgrade the upgrade of the helmchart from 6.43.5 to 6.44.9 receiving this issue in the flux2 helmrelease 

```
 parse error at (grafana/templates/deployment.yaml:1): function "grafana" not defined
```
not sure what's the issue but maybe it's known issue.

**Comment by muhlba91** [comment] 2022-12-02 18:12
same here using `helm template` with custom values.

**Comment by muhlba91** [comment] 2022-12-05 20:39
@mo-saeed do you have the `notifiers` sidecar enabled?

the error i had was related to the `searchNamespace` of the notifiers sidecar. once i disabled this sidecar it started working.
i don‘t use those, so it wasn‘t a problem for me.

as far as i can tell the interpolation for notifiers‘ `searchNamespace` is not correct after the update -> seems like no one is using these. ^^

i‘ll try to find some time to fix this interpolation and create a PR.

**Comment by ikogan** [comment] 2022-12-06 19:04
I'm getting this when trying to do a standard `helm install`, no flux. It does look like it's indeed a duplicate of #2044. I'm using the sidecar for dashboards actively and wanted to start using it for notifiers as well.

**Closed** 2022-12-07 16:34 UTC
