### ISSUE TITLE
[loki-distributed] config.expand-env=true not expanding

### ISSUE THREAD

**Issue by pblgomez** [grafana/helm-charts#1100] opened 2022-03-10 14:23 UTC
I'm trying to not hardcode values as I'm using ArgoCD so I have a secret with AWS credentials

secrets.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: xxx
  AWS_SECRET_ACCESS_KEY: xxx
  AWS_DEFAULT_REGION: xxx
```

values.yaml
```yaml
  querier:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-secrets
  loki:
    config: |
      storageConfig:
        aws:
          region: ${AWS_DEFAULT_REGION}
```

I can see the pod executing with Arguments: `-config.file=/etc/loki/config/config.yaml -target=querier -config.expand-env=true
`, inside the pod I can execute

```sh
$ echo ${AWS_DEFAULT_REGION}
us-east-1
```

but inside `/etc/loki/config/config.yaml` I see:

```yaml
storage_config:
  aws:
    region: ${AWS_DEFAULT_REGION}
```

why is it not expanding, what am I missing?

**Comment by sanjayka** [comment] 2022-09-13 11:19
@pblgomez ,
Hope this helps you - https://github.com/grafana/loki/issues/7110

**Comment by Rezkmike** [comment] 2022-10-05 02:54
I tested by adding  ```-config.expand-env=true``` manually inside the deployment-ingester.yaml file and it works as intended. Even though the variable inside config.yaml is not expanded when i checked in pod.

**Closed** 2022-10-26 13:08 UTC
